Что означает использование final при в данном объявлении?

try {
   ...
} catch (final Exception e) {
   ...
}
Использование final при объявлении переменной исключения в блоке catch означает, 
что эту переменную нельзя переназначить после её инициализации.
То есть, внутри блока catch переменная e всегда будет ссылаться на изначально 
перехваченное исключение, и её значение не может быть изменено. 